apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: tejaskalal/backend:b0cc90dc0e4a508ec80cda85d61d5d72df1f758f
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: redis
