apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: tejaskalal/backend:180b5a88b7cac8ab001c91de9ae39bae49257ab0
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: redis
