apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: tejaskalal/backend:ea09932b907c76ff72dfc8085139cfa8d73bb153
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: redis
