apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: tejaskalal/worker:70868778a69b7d145db10a577d9d3c8f8e61a910
          env:
            - name: REDIS_HOST
              value: redis
