apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: tejaskalal/worker:841e163d03707a99840065acf76c83e7f1287af8
          env:
            - name: REDIS_HOST
              value: redis
